---
apiVersion: v1
kind: Pod
metadata: 
 name: redis
 labels: 
  name: redis
  tier: db
spec:
 containers:
 - name: rabbitmq
   imagePullPolicy: Always
   image: rabbitmq
   ports:
    - containerPort: 5672
    - containerPort: 15672
---
apiVersion: v1
kind: Pod
metadata: 
 name: rabbitmq
 labels: 
  name: rabbitmq
  tier: db
spec:
 clusterIP: None
 selector:
  name: rabbitmq
 spec:
  selector:
  name: rabbitmq
  tier: db
 ports:   
 - ports: 5672
   name: amqp
 - ports: 15672
   name: http
  type: ClusterIP
---
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      name: rabbitmq  # has to match .spec.template.metadata.labels
      tier: db
  serviceName:  rabbitmq "
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        name: rabbitmq  # has to match .spec.selector.matchLabels
        tier: db
    spec:
      containers:
      - name: rabbitmq 
        image: sekharmanduri/rabbitmq:v1 
        ports:
        - containerPort: 27017
          name: rabbitmq
        volumeMounts:
        - name: rabbitmq-volume
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: 1Gi