---
apiVersion: v1
kind: ConfigMap
metadata:
 name: mysql-config
data:
 MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
 MYSQL_DATABASE: "cities"
---
apiVersion: v1
kind: Secret
metadata:
 name: mysql-secret
type: Opaque
data:
 MYSQL_USER: c2VjcmVO=
 MYSQL_PASSWORD: cm9vDEyMw
---
apiVersion: v1
kind: Pod
metadata: 
 name: mysql
 labels: 
  name: mysql
  tier: db
spec:
 containers:
 - name: mysql
   imagePullPolicy: Always
   envFrom:
  - configMapRef:
     name: mysql-config
  - secretRef:
     name: mysql-secret
   ports:
    - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata: 
 name: mysql
spec:
 selector:
  name: mysql
  tier: frontend
 ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      name: mysql  # has to match .spec.template.metadata.labels
      tier: db
  serviceName:  mysql "
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        name: mysql  # has to match .spec.selector.matchLabels
        tier: db
    spec:
      containers:
      - name: mysql 
        image: sekharmanduri mysql:v1 
        ports:
        - containerPort: 27017
          name: mysql
        volumeMounts:
        - name: mysql-volume
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: mysql-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: 1Gi