---
apiVersion: v1
kind: ConfigMap
metadata:
 name: catalogue-config
data:
 MONGO_URL: "mongodb://mongodb-service:80/catalogue"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    name: catalogue
    tier: app
spec:
  replicas: 1
  containers:
    - name: catalogue
      imagePullPolicy: Always
      image: sekharmanduri/catalogue: v1
      tier: app
  template:
    metadata:
      labels:
        name: catalogue
        tier: app
    spec:
      containers:
      - name: catalogue
        imagePullPolicy: Always
        image: sekharamanduri/catalogue:v1
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata: 
 name: catalogue
spec:
 selector:
  name: catalogue
  tier: app
 ports:
  - protocol: TCP
    port: 80
    targetPort: 8080