---
apiVersion: v1
kind: ConfigMap
metadata:
 name: user-config
data:
 REDIS_HOST: "redis"
 MONGO_URL: "mongodb://mongodb:27017/catalogue"
---
apiVersion: v1
kind: Pod
metadata: 
 name: user
 labels: 
  name: user
  tier: db
spec:
 containers:
 - name: user
   imagePullPolicy: Always
   image: sekharmanduri/user:v1
   envFrom:
   - configMapRef:
     name: user-config
   resources:
    requests:
     cpu: "100m"
     memory: "128Mi"
   limits:
     cpu: "100m"
     memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata: 
 name: user
spec:
 selector:
  name: user
  tier: frontend
 ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
