---
apiVersion: v1
kind: ConfigMap
metadata:
 name: web-config
data:
 REDIS_HOST: "redis"
 MONGO_URL: "mongodb://mongodb:27017/catalogue"
---
apiVersion: v1
kind: Pod
metadata: 
 name: web
 labels: 
  name: web
  tier: db
spec:
 containers:
 - name: web
   imagePullPolicy: Always
   image: sekharmanduri web:v1
   envFrom:
   - configMapRef:
     name: web-config
   resources:
    requests:
     cpu: "100m"
     memory: "128Mi"
   limits:
     cpu: "100m"
     memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata: 
 name: web
spec:
 selector:
  name: web
  tier: web
 ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: web hpa
  namespace: roboshop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web
  minReplicas: 1
  maxReplicas: 10
    - type: object
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50